#cloud-config

rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.10.28/27
        gateway: 192.168.10.1
        mtu: 1500
        dhcp: false
    dns:
      nameservers:
      - 192.168.10.1
      - 8.8.4.4

ssh_authorized_keys:
  - ssh-rsa INSERT-PUBLIC-KEY-HERE